export const privilegeDataJson = `[
    {
        "FunctionId":"CreateContract",
        "Note":"新建合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchContract",
        "Note":"查询合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContract",
        "Note":"编辑合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteContract",
        "Note":"作废合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"PrintContract",
        "Note":"打印合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishContract",
        "Note":"完成合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishContract",
        "Note":"撤销完成合同",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishGoods",
        "Note":"完成收发货",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishGoods",
        "Note":"撤销完成收发货",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishPayment",
        "Note":"完成收付款",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishPayment",
        "Note":"撤销完成收付款",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishInvoice",
        "Note":"完成收开票",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishInvoice",
        "Note":"撤销完成收开票",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateContractApproval",
        "Note":"新建合同审批",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelContractApproval",
        "Note":"撤销合同审批",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteContractApproval",
        "Note":"作废合同审批",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateReceivingGoodsRecord",
        "Note":"新建收货记录",
        "Category":3,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchReceivingGoodsRecord",
        "Note":"查询收货记录",
        "Category":3,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateReceivingGoodsRecord",
        "Note":"编辑收货记录",
        "Category":3,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteReceivingGoodsRecord",
        "Note":"删除收货记录",
        "Category":3,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateSendingGoodsRecord",
        "Note":"新建发货记录",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchSendingGoodsRecord",
        "Note":"查询发货记录",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateSendingGoodsRecord",
        "Note":"编辑发货记录",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteSendingGoodsRecord",
        "Note":"删除发货记录",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateSendingNotification",
        "Note":"新建发货通知单",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateSendingNotification",
        "Note":"编辑发货通知单",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteSendingNotification",
        "Note":"删除发货通知单",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchSendingNotification",
        "Note":"查看发货通知单",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateDeliveryNotificationApproval",
        "Note":"新建发货申请审批",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelDeliveryNotificationApproval",
        "Note":"撤销发货申请审批",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteDeliveryNotificationApproval",
        "Note":"作废发货申请审批",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SetDeliveryNoficationVerify",
        "Note":"复核发货申请",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelSetDeliveryNoficationVerify",
        "Note":"取消复核发货申请",
        "Category":49,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"PrintDeliveryConfirm",
        "Note":"打印收货确认函",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateReceiverCompany",
        "Note":"编辑提货单位",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPaymentApplication",
        "Note":"查询付款申请",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePaymentApplication",
        "Note":"新建付款申请",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdatePaymentApplication",
        "Note":"编辑付款申请",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeletePaymentApplication",
        "Note":"删除付款申请",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePayRequestApproval",
        "Note":"新建付款申请审批",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelPayRequestApproval",
        "Note":"撤销付款申请审批",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoletePayRequestApproval",
        "Note":"作废付款申请审批",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CompletePayRequestAmount",
        "Note":"完成付款",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelCompletePayRequestAmount",
        "Note":"取消完成付款",
        "Category":5,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"PrintInvoiceRecord",
        "Note":"打印开票申请",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchInvoiceRecord",
        "Note":"查询开票申请",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateInvoiceRecord",
        "Note":"新建开票申请",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateInvoiceRecord",
        "Note":"编辑开票申请",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteInvoiceRecord",
        "Note":"删除开票申请",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishOpenInvoice",
        "Note":"完成开票",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishOpenInvoice",
        "Note":"取消完成开票",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateInvoiceApproval",
        "Note":"新建开票申请",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelInvoiceApproval",
        "Note":"撤销开票申请审批",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteInvoiceApproval",
        "Note":"作废开票申请审批",
        "Category":6,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateReceiveInvoiceRecord",
        "Note":"新建收票记录",
        "Category":7,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchReceiveInvoiceRecord",
        "Note":"查询收票记录",
        "Category":7,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateReceiveInvoiceRecord",
        "Note":"编辑收票记录",
        "Category":7,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteReceiveInvoiceRecord",
        "Note":"删除收票记录",
        "Category":7,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"PrintReceiveInvoiceRecord",
        "Note":"打印收票记录",
        "Category":7,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateBalanceSettlement",
        "Note":"新建尾款结算",
        "Category":8,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchBalanceSettlement",
        "Note":"查询尾款结算",
        "Category":8,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateBalanceSettlement",
        "Note":"编辑尾款结算",
        "Category":8,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteBalanceSettlement",
        "Note":"删除尾款结算",
        "Category":8,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishBalanceSettlement",
        "Note":"完成尾款结算",
        "Category":8,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishBalanceSettlement",
        "Note":"取消完成尾款结算",
        "Category":8,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchStorage",
        "Note":"查询库存",
        "Category":9,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateStorageConvert",
        "Note":"新建货物转换",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchStorageConvert",
        "Note":"查询货物转换",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateStorageConvert",
        "Note":"编辑货物转换",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteStorageConvert",
        "Note":"删除货物转换",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateInventoryAdjustmentApproval",
        "Note":"新建库存调差审批",
        "Category":46,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelInventoryAdjustmentApproval",
        "Note":"撤销库存调差审批",
        "Category":46,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteInventoryAdjustmentApproval",
        "Note":"作废库存调差审批",
        "Category":46,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateStorageConversionApproval",
        "Note":"新建货物转换审批",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelStorageConversionApproval",
        "Note":"撤销货物转换审批",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteStorageConversionApproval",
        "Note":"作废货物转换审批",
        "Category":45,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchLedgerReport",
        "Note":"查询综合报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchContractJournalReport",
        "Note":"查询合同采销对应报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchStorageReport",
        "Note":"查询库存报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchContractExcuteRiskReport",
        "Note":"查询合同执行风险报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchTradeRiskReport",
        "Note":"查询客户信用报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchDeliveryOutInDailyReport",
        "Note":"查询出入库日报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchCustomer",
        "Note":"查询客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCustomer",
        "Note":"新建客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateCustomer",
        "Note":"编辑客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteCustomer",
        "Note":"删除客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DisableCustomer",
        "Note":"禁用客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"EnableCustomer",
        "Note":"启用客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"LockCustomer",
        "Note":"锁定客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UnLockCustomer",
        "Note":"解锁客户",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCompanyBankInfo",
        "Note":"新建银行账户",
        "Category":40,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateCompanyBankInfo",
        "Note":"编辑银行账户",
        "Category":40,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteCompanyBankInfo",
        "Note":"删除银行账户",
        "Category":40,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"EnableCompanyBankInfo",
        "Note":"启用银行账户",
        "Category":40,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DisableCompanyBankInfo",
        "Note":"停用银行帐户",
        "Category":40,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateWarehouse",
        "Note":"新建仓库",
        "Category":33,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchWarehouse",
        "Note":"查询仓库",
        "Category":33,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateWarehouse",
        "Note":"编辑仓库",
        "Category":33,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteWarehouse",
        "Note":"删除仓库",
        "Category":33,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DisableWarehouse",
        "Note":"停用仓库",
        "Category":33,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"EnableWarehouse",
        "Note":"启用仓库",
        "Category":33,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchCreditRating",
        "Note":"查询信用评级",
        "Category":36,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCreditRating",
        "Note":"新建信用评级",
        "Category":36,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateCreditRating",
        "Note":"编辑信用评级",
        "Category":36,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteCreditRating",
        "Note":"删除信用评级",
        "Category":36,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchContact",
        "Note":"查询通讯录",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateContact",
        "Note":"新建通讯录",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContact",
        "Note":"编辑通讯录",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteContact",
        "Note":"删除通讯录",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DisableCorporationType",
        "Note":"禁用公司类型",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"EnableCorporationType",
        "Note":"启用公司类型",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCorporationType",
        "Note":"新建公司类型",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateCorporationType",
        "Note":"编辑公司类型",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteCorporationType",
        "Note":"删除公司类型",
        "Category":35,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchGroup",
        "Note":"查询信用组",
        "Category":39,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UnLockGroup",
        "Note":"解锁信用组",
        "Category":39,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"LockedGroup",
        "Note":"锁定信用组",
        "Category":39,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateGroup",
        "Note":"新增信用组",
        "Category":39,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateGroup",
        "Note":"编辑信用组",
        "Category":39,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteGroup",
        "Note":"删除信用组",
        "Category":39,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishFirePrice",
        "Note":"撤销完成点价",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishFirePrice",
        "Note":"完成点价",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateFirePriceApproval",
        "Note":"新建点价确认函审批",
        "Category":44,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFirePriceApproval",
        "Note":"撤销点价确认函审批",
        "Category":44,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteFirePriceApproval",
        "Note":"作废点价确认函审批",
        "Category":44,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateFirePrice",
        "Note":"新建点价记录",
        "Category":41,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateFirePrice",
        "Note":"编辑点价记录",
        "Category":41,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteFirePrice",
        "Note":"删除点价记录",
        "Category":41,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateFireConfirm",
        "Note":"新建点价确认函",
        "Category":44,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateFireConfirm",
        "Note":"编辑点价确认函",
        "Category":44,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteFireConfirm",
        "Note":"删除点价确认函",
        "Category":44,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePostponedFireConfirm",
        "Note":"新建延期点价确认函",
        "Category":43,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdatePostponedFireConfirm",
        "Note":"编辑延期点价确认函",
        "Category":43,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeletePostponedFireConfirm",
        "Note":"删除延期点价确认函",
        "Category":43,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePostponedFirePriceApproval",
        "Note":"新建延期点价确认函审批",
        "Category":43,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelPostponedFirePriceApproval",
        "Note":"撤销延期点价确认函审批",
        "Category":43,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoletePostponedFirePriceApproval",
        "Note":"作废延期点价确认函审批",
        "Category":43,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManageFirePrice",
        "Note":"价格管理",
        "Category":13,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManagePriceAdjustment",
        "Note":"价格调整",
        "Category":13,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManageCargoPriceMapping",
        "Note":"货价匹配",
        "Category":13,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePriceConfirm",
        "Note":"新建价格确认单",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdatePriceConfirm",
        "Note":"编辑价格确认单",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeletePriceConfirm",
        "Note":"删除价格确认单",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePriceConfirmApproval",
        "Note":"新建价格确认单审批",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelPriceConfirmApproval",
        "Note":"撤销价格确认单审批",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoletePriceConfirmApproval",
        "Note":"作废价格确认单审批",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPriceConfirm",
        "Note":"查询价格确认单",
        "Category":42,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCompanyCreditRatingModificationApproval",
        "Note":"新建客户信用评级调整审批",
        "Category":15,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelCompanyCreditRatingModificationApproval",
        "Note":"撤销客户信用评级调整审批",
        "Category":15,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteCompanyCreditRatingModificationApproval",
        "Note":"作废客户信用评级调整审批",
        "Category":15,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchExchangeBill",
        "Note":"查询票据",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateExchangeBill",
        "Note":"创建票据",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateExchangeBill",
        "Note":"编辑票据",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteExchangeBill",
        "Note":"删除票据",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchMoneyConversion",
        "Note":"查询票据贴现",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateMoneyConversion",
        "Note":"创建票据贴现",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateMoneyConversion",
        "Note":"编辑票据贴现",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteMoneyConversion",
        "Note":"删除票据贴现",
        "Category":16,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchLetterOfCredit",
        "Note":"查询信用证",
        "Category":47,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateLetterOfCredit",
        "Note":"创建信用证",
        "Category":47,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateLetterOfCredit",
        "Note":"编辑信用证",
        "Category":47,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteLetterOfCredit",
        "Note":"删除信用证",
        "Category":47,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchCommercialInvoice",
        "Note":"查询商业发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCommercialInvoice",
        "Note":"新建商业发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateCommercialInvoice",
        "Note":"编辑商业发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteCommercialInvoice",
        "Note":"删除商业发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"PrintCommercialInvoice",
        "Note":"打印商业发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCommercialInvoiceApproval",
        "Note":"新建商业发票审批",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelCommercialInvoiceApproval",
        "Note":"撤销商业发票审批",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoleteCommercialInvoiceApproval",
        "Note":"作废商业发票审批",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"PostingInvoice",
        "Note":"过账发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ReversalInvoice",
        "Note":"冲销发票",
        "Category":17,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPledgeContract",
        "Note":"查看质押／赎回合同",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePledgeContract",
        "Note":"创建质押／赎回合同",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdatePledgeContract",
        "Note":"修改质押／赎回合同",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeletePledgeContract",
        "Note":"删除质押／赎回合同",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"FinishPledgeContract",
        "Note":"完成质押／赎回合同",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelFinishPledgeContract",
        "Note":"取消完成质押／赎回合同",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPledgeRenewal",
        "Note":"查看质押展期",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePledgeRenewal",
        "Note":"创建质押展期",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdatePledgeRenewal",
        "Note":"修改质押展期",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeletePledgeRenewal",
        "Note":"删除质押展期",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePledgeRenewalApproval",
        "Note":"新建／提交展期申批",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelPledgeRenewalApproval",
        "Note":"撤销展期申批",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoletePledgeRenewalApproval",
        "Note":"作废展期申批",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePledgeContractApproval",
        "Note":"新建质押合同审批",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CancelPledgeContractApproval",
        "Note":"撤销质押合同审批",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ObsoletePledgeContractApproval",
        "Note":"作废质押合同审批",
        "Category":18,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchDeposit",
        "Note":"查看保证金",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateDeposit",
        "Note":"创建保证金",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateDeposit",
        "Note":"修改保证金",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteDeposit",
        "Note":"删除保证金",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchCarry",
        "Note":"查看结转记录",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateCarry",
        "Note":"创建结转记录",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateCarry",
        "Note":"修改结转记录",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteCarry",
        "Note":"删除结转记录",
        "Category":19,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateReceivingClaim",
        "Note":"新增款项流水记录",
        "Category":20,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateReceivingClaim",
        "Note":"编辑款项流水记录",
        "Category":20,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteReceivingClaim",
        "Note":"删除款项流水记录",
        "Category":20,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchReceivingClaim",
        "Note":"查看款项流水记录",
        "Category":20,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchRiskControlParameters",
        "Note":"查看风险控制参数",
        "Category":22,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateRiskControlParameters",
        "Note":"修改风险控制参数",
        "Category":22,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreatePaymentRecord",
        "Note":"新建付款记录",
        "Category":24,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdatePaymentRecord",
        "Note":"编辑付款记录",
        "Category":24,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeletePaymentRecord",
        "Note":"删除付款记录",
        "Category":24,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPaymentRecord",
        "Note":"查询付款记录",
        "Category":24,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateReceivingPaymentRecord",
        "Note":"新建收款记录",
        "Category":25,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateReceivingPaymentRecord",
        "Note":"编辑收款记录",
        "Category":25,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteReceivingPaymentRecord",
        "Note":"删除收款记录",
        "Category":25,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchReceivingPaymentRecord",
        "Note":"查询收款记录",
        "Category":25,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchArchive",
        "Note":"查询存档",
        "Category":32,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateArchive",
        "Note":"新建存档",
        "Category":32,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateArchive",
        "Note":"编辑存档",
        "Category":32,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteArchive",
        "Note":"删除存档",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManageAccountPeriod",
        "Note":"财务账期配置",
        "Category":28,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManageCustomerBusinessConfiguration",
        "Note":"管理客户业务配置",
        "Category":30,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManageWarehouseBusinessConfiguration",
        "Note":"管理仓库业务配置",
        "Category":30,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"ManageBankAccountBusinessConfiguration",
        "Note":"管理银行帐号业务配置",
        "Category":30,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchTradeInstruction",
        "Note":"查询业务指令",
        "Category":31,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateTradeInstruction",
        "Note":"新增业务指令",
        "Category":31,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"EditTradeInstruction",
        "Note":"编辑业务指令",
        "Category":31,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteTradeInstruction",
        "Note":"删除业务指令",
        "Category":31,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContractWeight",
        "Note":"编辑合同重量",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchTradePricing",
        "Note":"查询计价量",
        "Category":50,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContractCostomers",
        "Note":"编辑合同客户",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateTransportInfo",
        "Note":"编辑发货运输信息",
        "Category":4,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContractPricingTerm",
        "Note":"编辑合同结算条款",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContractExcutor",
        "Note":"编辑执行人员",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateContractTradingStrategy",
        "Note":"编辑策略",
        "Category":1,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"QueryFeeBill",
        "Note":"查询费用结算",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateFeeBill",
        "Note":"新增费用结算",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateFeeBill",
        "Note":"编辑费用结算",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteFeeBill",
        "Note":"删除费用结算",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"QueryFeeInvoice",
        "Note":"查询费用发票",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"CreateFeeInvoice",
        "Note":"新增费用发票",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"UpdateFeeInvoice",
        "Note":"编辑费用发票",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"DeleteFeeInvoice",
        "Note":"删除费用发票",
        "Category":56,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchDeliveryPendingReport",
        "Note":"查看待收发货报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPendingPriceReport",
        "Note":"查看待点价报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchInvoiceReport",
        "Note":"查看待收开票报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"SearchPendingReceivePayReport",
        "Note":"查看应收应付报表",
        "Category":10,
        "Modules":[
            2
        ]
    },
    {
        "FunctionId":"H_SearchAcPurchasingCost",
        "Note":"采购成本-查询",
        "Category":706,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcPurchasingCost",
        "Note":"采购成本-导出",
        "Category":706,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcStressTestReport",
        "Note":"压力测试报表-导出",
        "Category":706,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcStressTestReport",
        "Note":"压力测试报表-查询",
        "Category":706,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcStatementFutureTradeRecord",
        "Note":"结算单交易记录-查询",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcStatementFutureTradeRecord",
        "Note":"结算单交易记录-添加",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcStatementFutureTradeRecord",
        "Note":"结算单交易记录-修改",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcStatementFutureTradeRecord",
        "Note":"结算单交易记录-删除",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcStatementFutureTradeRecord",
        "Note":"结算单交易记录-导出",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcStatementTaEquityRecord",
        "Note":"结算单权益记录-查询",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcStatementTaEquityRecord",
        "Note":"结算单权益记录-导出",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcStatementTaEquityRecord",
        "Note":"结算单权益记录-添加",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcStatementTaEquityRecord",
        "Note":"结算单权益记录-修改",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcStatementTaEquityRecord",
        "Note":"结算单权益记录-删除",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcMarginRate",
        "Note":"保证金率配置-查询",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcMarginRate",
        "Note":"保证金率配置-添加",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcMarginRate",
        "Note":"保证金率配置-修改",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcMarginRate",
        "Note":"保证金率配置-删除",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportAcMarginRate",
        "Note":"保证金率配置-导入",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcMarginRate",
        "Note":"保证金率配置-导出",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateProfitCenterAccountPositionReport",
        "Note":"利润中心持仓-新增",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateProfitCenterAccountPositionReport",
        "Note":"利润中心持仓-编辑",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"Mdm_CorporationManager",
        "Note":"法人管理",
        "Category":300,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_DepartmentManager",
        "Note":"部门管理",
        "Category":300,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_UserManager",
        "Note":"用户管理",
        "Category":300,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ProfitCenterManager",
        "Note":"利润中心管理",
        "Category":300,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CommodityManager",
        "Note":"品种管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_BrandManager",
        "Note":"品牌管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CurrencyManager",
        "Note":"币种管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_QuantityManager",
        "Note":"量管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_UnitManager",
        "Note":"单位管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_BrokerManager",
        "Note":"经纪公司管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TradeAccountManager",
        "Note":"资金账户管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TaxRateManager",
        "Note":"税率管理",
        "Category":306,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CodeTemplateManager",
        "Note":"编号模板管理",
        "Category":306,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_SystemCodeManager",
        "Note":"系统编号管理",
        "Category":306,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_DocTemplateManager",
        "Note":"单据模板管理",
        "Category":306,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_MarkteManager",
        "Note":"作价市场管理",
        "Category":302,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_MarketCalendarManager",
        "Note":"交易日历管理",
        "Category":302,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_InstrumentCategoryManager",
        "Note":"标准合约管理",
        "Category":302,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_InstrumentManager",
        "Note":"具体合约管理",
        "Category":302,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ApprovalSwitchManager",
        "Note":"审批开关管理",
        "Category":303,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ApprovalRoleManager",
        "Note":"审批角色管理",
        "Category":303,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ApprovalTemplatetManager",
        "Note":"审批流程模板管理",
        "Category":303,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_BuinessApprovalManager",
        "Note":"业务审批流程管理",
        "Category":303,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ApprovalConditionManager",
        "Note":"条件引擎管理",
        "Category":303,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ApprovalGrantManager",
        "Note":"审批转授权",
        "Category":303,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_SystemParametersManager",
        "Note":"系统参数配置",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_SystemServiceManager",
        "Note":"系统后台服务",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ReSendMesgManager",
        "Note":"审批相关运维",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_SystemLogManager",
        "Note":"系统操作日志",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_SubscribeConfigManager",
        "Note":"消息订阅管理",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_BuinessManager",
        "Note":"业务管理",
        "Category":306,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TradingStrategyManager",
        "Note":"策略管理",
        "Category":301,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CapitalPoolManager",
        "Note":"资金池配置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CorporationGroupManager",
        "Note":"法人组配置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_PerOrderLotsLimitManager",
        "Note":"单次下单手数限制设置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_PositionLimitManager",
        "Note":"持仓限制设置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_AllowedTicks",
        "Note":"下单价格限制",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ClosableTicks",
        "Note":"优先平仓配置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_FutureServicesManage",
        "Note":"期货服务通道",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TradeAccountConnManager",
        "Note":"资金账户连接",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_FutureMobilesManage",
        "Note":"手机设备管理",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_StandardData",
        "Note":"标准数据配置",
        "Category":308,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_UserDataUpdload",
        "Note":"系统数据上传",
        "Category":308,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ApprovalConfigUpload",
        "Note":"审批流程配置",
        "Category":308,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_StandardDataSubscribe",
        "Note":"数据订阅配置",
        "Category":308,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CtpMappingAdapter",
        "Note":"CTP通道配置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ReSendMesgManager_Patial",
        "Note":"消息中心",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_CqgMappingAdapter",
        "Note":"CQG通道配置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TsPatsServiceChannelManager",
        "Note":"PATS通道配置",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TsPatsOriginalOrderTypeManager",
        "Note":"PATS原始报单类型",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TsPatsOriginalContractsManager",
        "Note":"PATS原始标准合约",
        "Category":305,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_WeChatConfigManage",
        "Note":"微信配置管理",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_DingTalkConfigManage",
        "Note":"钉钉配置管理",
        "Category":304,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_PaymentTypeManager",
        "Note":"收支类型管理",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_FutureAccounting",
        "Note":"标准合约清算",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TradeAccounting",
        "Note":"现货清算",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_ProfitCenterAccounting",
        "Note":"利润中心清算",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_TradeAccountAccounting",
        "Note":"资金账户清算",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_EquityTypeManager",
        "Note":"权益类型",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_FeeCategoryManager",
        "Note":"费用分类管理",
        "Category":306,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_AcProfitCenterBudgetConf",
        "Note":"利润中心授权",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"Mdm_AcStrategyAuthorize",
        "Note":"策略授权",
        "Category":307,
        "Modules":[
            1
        ]
    },
    {
        "FunctionId":"HF_SearchHedgeExecuteInstruction",
        "Note":"套保指令-查询",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateHedgeExecuteInstruction",
        "Note":"套保指令-新增",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_UpdateHedgeExecuteInstruction",
        "Note":"套保指令-编辑",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteHedgeExecuteInstruction",
        "Note":"套保指令-删除",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchExposureBalance",
        "Note":"敞口对冲-查询",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateExposureBalance",
        "Note":"敞口对冲-新增",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteExposureBalance",
        "Note":"敞口对冲-删除",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchRiskExposure",
        "Note":"风险敞口-查询",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateRiskExposure",
        "Note":"风险敞口-新增",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_UpdateRiskExposure",
        "Note":"风险敞口-编辑",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteRiskExposure",
        "Note":"风险敞口-删除",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_ImportRiskExposure",
        "Note":"风险敞口-导入",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_ExportRiskExposure",
        "Note":"风险敞口-导出",
        "Category":500,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchFutureMovePosition",
        "Note":"期货移仓-查询",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateFutureMovePosition",
        "Note":"期货移仓-新增",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteFutureMovePosition",
        "Note":"期货移仓-删除",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchHedgingMatch",
        "Note":"套保匹配-查询",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateHedgingMatch",
        "Note":"套保匹配-创建",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteHedgingMatch",
        "Note":"套保匹配-删除",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchFutureTradeRecord",
        "Note":"期货交易记录-查询",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_ExportHedgingMatch",
        "Note":"期货交易记录-导出",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchFutureClosePosition",
        "Note":"期货开平匹配-查询",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateFutureClosePosition",
        "Note":"期货开平匹配-新增",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteFutureClosePosition",
        "Note":"期货开平匹配-删除",
        "Category":502,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchInstructionExposureMatch",
        "Note":"指令敞口匹配-查询",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateInstructionExposureMatch",
        "Note":"指令敞口匹配-新增",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteInstructionExposureMatch",
        "Note":"指令敞口匹配-删除",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchInstructionMatchInventory",
        "Note":"撮合清单-查看",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_CreateInstructionMatchInventoryTR",
        "Note":"撮合清单虚拟成交记录-创建",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_DeleteInstructionMatchInventoryTR",
        "Note":"撮合清单虚拟成交记录-删除",
        "Category":501,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchHedgeRiskReport",
        "Note":"套保风险报表-查看",
        "Category":503,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"HF_SearchHedgeLedgerReport",
        "Note":"套保台账报表-查看",
        "Category":503,
        "Modules":[
            32
        ]
    },
    {
        "FunctionId":"H_SearchInstrumentFeed",
        "Note":"合约行情-查询",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_CreateInstrumentFeed",
        "Note":"合约行情-新增",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_UpdateInstrumentFeed",
        "Note":"合约行情-编辑",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_DeleteInstrumentFeed",
        "Note":"合约行情-删除",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_ExportInstrumentFeed",
        "Note":"合约行情-导出",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_GetBloombergInstrumentFeed",
        "Note":"合约行情-对接彭博",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_SearchExchangeRate02",
        "Note":"外汇汇率-查询",
        "Category":601,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_CreateExchangeRate02",
        "Note":"外汇汇率-新增",
        "Category":601,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_UpdateExchangeRate02",
        "Note":"外汇汇率-编辑",
        "Category":601,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_DeleteExchangeRate02",
        "Note":"外汇汇率-删除",
        "Category":601,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_ExportExchangeRate02",
        "Note":"外汇汇率-导出",
        "Category":601,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_GetBloombergExchangeRate02",
        "Note":"外汇汇率-对接彭博",
        "Category":601,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_SearchBloombergInstrumentFeed",
        "Note":"彭博合约行情配置-查询",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_CreateBloombergInstrumentFeed",
        "Note":"彭博合约行情配置-新增",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_UpdateBloombergInstrumentFeed",
        "Note":"彭博合约行情配置-编辑",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_DeleteBloombergInstrumentFeed",
        "Note":"彭博合约行情配置-删除",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_SearchBloombergExchangeRate02",
        "Note":"彭博外汇汇率配置-查询",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_CreateBloombergExchangeRate02",
        "Note":"彭博外汇汇率配置-新增",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_UpdateBloombergExchangeRate02",
        "Note":"彭博外汇汇率配置-编辑",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_DeleteBloombergExchangeRate02",
        "Note":"彭博外汇汇率配置-删除",
        "Category":602,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_GetWindInstrumentFeed",
        "Note":"合约行情-对接万得",
        "Category":600,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_SearchWindInstrumentFeed",
        "Note":"万得合约行情配置-查询",
        "Category":603,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_CreateWindInstrumentFeed",
        "Note":"万得合约行情配置-新增",
        "Category":603,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_UpdateWindInstrumentFeed",
        "Note":"万得合约行情配置-编辑",
        "Category":603,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_DeleteWindInstrumentFeed",
        "Note":"万得合约行情配置-删除",
        "Category":603,
        "Modules":[
            64
        ]
    },
    {
        "FunctionId":"H_RealTimeRiskControlList",
        "Note":"实时期货风控-列表",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcSpotTradeRecord",
        "Note":"现货交易记录-查询",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcSpotTradeRecord",
        "Note":"现货交易记录-新增",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcSpotTradeRecord",
        "Note":"现货交易记录-编辑",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcSpotTradeRecord",
        "Note":"现货交易记录-删除",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcSpotTradeRecord",
        "Note":"现货交易记录-导出",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcFutureTradeRecord",
        "Note":"期货交易记录-查询",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcFutureTradeRecord",
        "Note":"期货交易记录-新增",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcFutureTradeRecord",
        "Note":"期货交易记录-编辑",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcFutureTradeRecord",
        "Note":"期货交易记录-删除",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcFutureTradeRecord",
        "Note":"期货交易记录-导出",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcOtherPaymentRecord",
        "Note":"其他收支记录-查询",
        "Category":702,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcOtherPaymentRecord",
        "Note":"其他收支记录-新增",
        "Category":702,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcOtherPaymentRecord",
        "Note":"其他收支记录-编辑",
        "Category":702,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcOtherPaymentRecord",
        "Note":"其他收支记录-删除",
        "Category":702,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcOtherPaymentRecord",
        "Note":"其他收支记录-导出",
        "Category":702,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcSpotPosition",
        "Note":"现货持仓-查询",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcSpotPosition",
        "Note":"现货持仓-导出",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcFuturePosition",
        "Note":"期货持仓-查询",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcFuturePosition",
        "Note":"期货持仓-导出",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcPnL",
        "Note":"利润表-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcPnL",
        "Note":"利润表-导出",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcCost",
        "Note":"费用表-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcCost",
        "Note":"费用表-导出",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcForexTradeRecord",
        "Note":"外汇交易记录-查询",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcForexTradeRecord",
        "Note":"外汇交易记录-新增",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcForexTradeRecord",
        "Note":"外汇交易记录-编辑",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcForexTradeRecord",
        "Note":"外汇交易记录-删除",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcForexTradeRecord",
        "Note":"外汇交易记录-导出",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcPositionForex",
        "Note":"外汇持仓-查询",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcPositionForex",
        "Note":"外汇持仓-导出",
        "Category":703,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcCapitalOccupation",
        "Note":"期货资金占用-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcCapitalOccupation",
        "Note":"期货资金占用-导出",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcCapitalOccupationSpot",
        "Note":"实时现货占用-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcCapitalOccupationSpot",
        "Note":"实时现货占用-导出",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcCapitalOccupationSpot02",
        "Note":"现货资金占用-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcCapitalOccupationSpot02",
        "Note":"现货资金占用-导出",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcGeneralDailyReport",
        "Note":"综合报表-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcRiskControlDailyReport",
        "Note":"策略报表-查询",
        "Category":706,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcStageProfitReport",
        "Note":"首页报表-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchCancelOrderCountReport",
        "Note":"撤单次数报表-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchFundStatusReport",
        "Note":"内盘资金状况表-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAccountPositionReport",
        "Note":"账户持仓-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchPortfolioContractPositionReport",
        "Note":"组合合约持仓-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchProfitCenterAccountPositionReport",
        "Note":"利润中心持仓-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchProfitCenterPnLReport",
        "Note":"利润中心资金-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CalculateAcFutureTradeRecord",
        "Note":"期货交易记录-清算手续费",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcCommissionRate",
        "Note":"手续费率-查询",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_AddAcCommissionRate",
        "Note":"手续费率-添加",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcCommissionRate",
        "Note":"手续费率-导出",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportAcCommissionRate",
        "Note":"手续费率-导入",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_EditAcCommissionRate",
        "Note":"手续费率-修改",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_RemovecCommissionRate",
        "Note":"手续费率-删除",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ReadMarginRate",
        "Note":"原始保证金率-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportMarginRate",
        "Note":"原始保证金率-导出",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ReadForeignAccountCashReport",
        "Note":"外盘资金状况表-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcMarginTier",
        "Note":"保证金期间-导出",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcMarginTier",
        "Note":"保证金期间-查询",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcMarginTier",
        "Note":"保证金期间-添加",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcMarginTier",
        "Note":"保证金期间-修改",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcMarginTier",
        "Note":"保证金期间-删除",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportAcMarginTier",
        "Note":"保证金期间-导入",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcTradeSettlementDateConfig",
        "Note":"外盘结算时间配置-查询",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcTradeSettlementDateConfig",
        "Note":"外盘结算时间配置-添加",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcTradeSettlementDateConfig",
        "Note":"外盘结算时间配置-修改",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcTradeSettlementDateConfig",
        "Note":"外盘结算时间配置-删除",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchOriginalFee",
        "Note":"原始手续费率-查询",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportOriginalFee",
        "Note":"原始手续费率-导出",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcInterSpreadMarginRate",
        "Note":"跨期保证金-导出",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcInterSpreadMarginRate",
        "Note":"跨期保证金-查询",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcInterSpreadMarginRate",
        "Note":"跨期保证金-添加",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcInterSpreadMarginRate",
        "Note":"跨期保证金-修改",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcInterSpreadMarginRate",
        "Note":"跨期保证金-删除",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportAcInterSpreadMarginRate",
        "Note":"跨期保证金-导入",
        "Category":709,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_GetAcFutureTradeRecord",
        "Note":"期货交易记录-获取",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateProfitCenterPnLReport",
        "Note":"利润中心资金-编辑",
        "Category":707,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchFutureTradeRecordFromOnlyOffSite",
        "Note":"场外单记录查看",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchStatementRecord",
        "Note":"结算单记录-查询",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteStatementRecord",
        "Note":"结算单记录-删除",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportStatementRecord",
        "Note":"结算单记录-导入",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateSettlementPrice",
        "Note":"结算价引用-新建",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchStatementReviewReport",
        "Note":"结算单复核报表-查询",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CalculateStatementReviewReport",
        "Note":"结算单复核报表-重算",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchStatementProfitReport",
        "Note":"结算单盈亏报表-查询",
        "Category":711,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcPnLReport",
        "Note":"期货利润-查看",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcPnLReport",
        "Note":"期货利润-导出",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcProfitCenterStatementReport",
        "Note":"利润中心结算单-导出",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcProfitCenterStatementReport",
        "Note":"利润中心结算单-查询",
        "Category":705,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcFuturePositionExceptionLog",
        "Note":"期货持仓-异常记录查询",
        "Category":701,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcSpotAveragePricingRecord",
        "Note":"现货均价信息-查询",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcSpotAveragePricingRecord",
        "Note":"现货均价信息-添加",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcSpotAveragePricingRecord",
        "Note":"现货均价信息-编辑",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcSpotAveragePricingRecord",
        "Note":"现货均价信息-删除",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportAcSpotAveragePricingRecord",
        "Note":"现货均价信息-导入",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcSpotAveragePricingRecord",
        "Note":"现货均价信息-导出",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAcSpotTailDiffrenceInfo",
        "Note":"现货尾差信息-查询",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_CreateAcSpotTailDiffrenceInfo",
        "Note":"现货尾差信息-新增",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_UpdateAcSpotTailDiffrenceInfo",
        "Note":"现货尾差信息-编辑",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_DeleteAcSpotTailDiffrenceInfo",
        "Note":"现货尾差信息-删除",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ImportAcSpotTailDiffrenceInfo",
        "Note":"现货尾差信息-导入",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_ExportAcSpotTailDiffrenceInfo",
        "Note":"现货尾差信息-导出",
        "Category":700,
        "Modules":[
            128
        ]
    },
    {
        "FunctionId":"H_SearchAccoutingPositionReport",
        "Note":"账户持仓报表-查询",
        "Category":701,
        "Modules":[
            256
        ]
    },
    {
        "FunctionId":"H_SearchProfitCenterPosition",
        "Note":"利润中心持仓-查询",
        "Category":900,
        "Modules":[
            256
        ]
    },
    {
        "FunctionId":"H_SearchProfitCenterProfit",
        "Note":"〼Privilege.利润中心盈亏-查询〼",
        "Category":900,
        "Modules":[
            256
        ]
    },
    {
        "FunctionId":"H_SearchAgentCapitalOccupancy",
        "Note":"账户可用资金-查询",
        "Category":900,
        "Modules":[
            256
        ]
    }
]`

export const PrivilegeCategory = `{
    "Contract":1,
    "ReceivingCargo":3,
    "SendingCargo":4,
    "PaymentApproval":5,
    "SendingInvoice":6,
    "ReceivingInvice":7,
    "BalanceSettlement":8,
    "Storage":9,
    "Report":10,
    "BasicData":11,
    "Approval":12,
    "Price":13,
    "OtherBill":14,
    "CreditRating":15,
    "BillManagement":16,
    "Invoice":17,
    "PledgeContract":18,
    "CashDeposit":19,
    "PaymentClaim":20,
    "FeeEstimate":21,
    "RiskControl":22,
    "Cargo":23,
    "Payment":24,
    "Gathering":25,
    "SystemData":26,
    "Other":27,
    "Finance":28,
    "SAP":29,
    "UserConfiguration":30,
    "TradeInstruction":31,
    "Archive":32,
    "BasicDataWarehouse":33,
    "BasicDataSettlementPrice":34,
    "BasicDataCompany":35,
    "BasicDataCreditRating":36,
    "BasicDataBrand":37,
    "BasicDataMaterial":38,
    "BasicDataGroup":39,
    "BasicDataBankInfo":40,
    "Pricing":41,
    "PriceConfirm":42,
    "PriceConfirmPostponed":43,
    "FirePriceConfirm":44,
    "StorageConvert":45,
    "StorageInventoryAdjustment":46,
    "LetterOfCredit":47,
    "ApprovalCancellationForm":48,
    "DeliveryNotification":49,
    "FutureTrade":50,
    "MarketPriceDiff":51,
    "ExchangeRate":52,
    "PaymentProposal":53,
    "Warehousing":54,
    "FreightRateManager":55,
    "FeeBillManager":56,
    "RC_Future":200,
    "RC_Spot":201,
    "RC_Forex":202,
    "RC_Option":203,
    "RC_Security":204,
    "RC_PaymentType":205,
    "RC_MarketQuotations":206,
    "RC_Report":207,
    "RC_SysConfig":208,
    "RC_SysMaintenance":209,
    "RC_MasterData":210,
    "RC_TradingAccount":211,
    "RC_Portfolio":212,
    "RC_Hedging":213,
    "RC_Fund":214,
    "RC_BillTradeRecord":215,
    "RC_FileArchive":216,
    "MdmOrgStructure":300,
    "MdmBasicData":301,
    "MdmExchangeManager":302,
    "MdmGrantManager":303,
    "MdmBasicMaintenance":304,
    "MdmFutureConfiguration":305,
    "MdmTradeConfiguration":306,
    "MdmAccountingConfiguration":307,
    "MdmConfiguration":308,
    "Project":400,
    "HfExposure":500,
    "HfHedging":501,
    "HfFuture":502,
    "HfReport":503,
    "InstrumentFeed":600,
    "ExchangeRate02":601,
    "BloombergConfig":602,
    "WindConfig":603,
    "AcSpotTradeMgr":700,
    "AcFutureTradeMgr":701,
    "AcOtherPaymentMgr":702,
    "AcForexTradeMgr":703,
    "AcPnLCost":705,
    "AcCapitalOccupation":706,
    "AcRiskControlReport":707,
    "AcTradeAccountReport":708,
    "AcSystemConfig":709,
    "AcSettlementDocumentReview":710,
    "AcStatementMgr":711,
    "FutureOrderReport":900,
    "_Notes":{
        "1":"合同",
        "3":"收货",
        "4":"发货",
        "5":"付款申请",
        "6":"开票",
        "7":"收票",
        "8":"尾款结算",
        "9":"库存",
        "10":"报表",
        "11":"基础数据",
        "12":"审批",
        "13":"价",
        "14":"系统外单据",
        "15":"客户信用评级",
        "16":"票据管理",
        "17":"发票",
        "18":"质押/赎回合同",
        "19":"保证金",
        "20":"款项流水",
        "21":"费用暂估",
        "22":"风控",
        "23":"货",
        "24":"付款",
        "25":"收款",
        "26":"系统配置数据",
        "27":"其他",
        "28":"财务",
        "29":"SAP",
        "30":"用户配置数据",
        "31":"业务指令",
        "32":"单据存档",
        "33":"基础数据-仓库",
        "34":"基础数据-行情",
        "35":"基础数据-客户",
        "36":"基础数据-客户信用评级",
        "37":"基础数据-品牌",
        "38":"基础数据-物料",
        "39":"基础数据-信用组",
        "40":"基础数据-银行账户",
        "41":"价-点价",
        "42":"价-价格确认单",
        "43":"价-延期点价确认函",
        "44":"价-点价确认函",
        "45":"库存-货物转换",
        "46":"库存-库存调差",
        "47":"票据管理-信用证",
        "48":"审批撤销单",
        "49":"发货申请",
        "50":"期货",
        "51":"市场价差",
        "52":"汇率",
        "53":"付款建议",
        "54":"仓储管理",
        "55":"运费管理",
        "56":"费用结算管理",
        "200":"期货",
        "201":"现货",
        "202":"外汇",
        "203":"期权",
        "204":"证券",
        "205":"其他收支",
        "206":"行情对接",
        "207":"管理报表",
        "208":"系统配置",
        "209":"系统运维",
        "210":"主数据",
        "211":"资金账户管理",
        "212":"组合/策略",
        "213":"套保",
        "214":"基金",
        "215":"票据",
        "216":"文件管理",
        "300":"组织架构",
        "301":"基础数据",
        "302":"市场数据",
        "303":"审批配置",
        "304":"系统运维",
        "305":"期货配置",
        "306":"现货配置",
        "307":"清算配置",
        "308":"快捷配置",
        "400":"项目",
        "500":"敞口管理",
        "501":"套保管理",
        "502":"期货管理",
        "503":"报表管理",
        "600":"合约行情",
        "601":"外汇汇率",
        "602":"彭博配置",
        "603":"万得配置",
        "700":"现货交易管理",
        "701":"期货交易管理",
        "702":"其他收支管理",
        "703":"外汇交易管理",
        "705":"基础清算报表",
        "706":"高级清算报表",
        "707":"盘中风控报表",
        "708":"账户报表",
        "709":"系统配置",
        "710":"结算单复核",
        "711":"结算单管理",
        "900":"期货平台报表"
    }
}`